server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 61613
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chat
    password: chatpass
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
secretToken: secreto