spring:
  rabbitmq:
    host: chat-rabbit
    port: 61613
    username: guest
  datasource:
    url: jdbc:mysql://${chat-db}:3306/chat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chat
    initialization-mode: ${initializationMode}
  jpa:
    hibernate:
      ddl-auto: ${ddlAuto}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"