name: "deploy"
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: echo "hola"
      - name: show directory
        run: ls